Welcome to a custom OpenShift Virtualization Roadshow !

== Introduction
This repository hosts the lab guide for the OpenShift Virtualization Roadshow, which can be delivered by Red Hat Associates to customers and interested parties all over the world.

It is designed to work with the Showroom lab environment provided by the Red Hat Demo Platform (RHDP) team.

This roadshow event is organized to allow you to have a hands-on experience with Red Hat OpenShift Virtualization.

OpenShift Virtualization enables you to bring virtual machines onto a modern, Kubernetes-based infrastructure. It enables the development and delivery of new applications as well as the modernization of existing ones and can create applications that consist of virtual machines, containers, and serverless functions - all managed together using Kubernetes-native tools and paradigms.

In this event we will explore many common management activities that virtual administrators often encounter in their day to day workflows.

== Who Will Benefit Most from attending a Roadshow?

*Virtual Machine Administrators* -- Those responsible for day to day management of virtual guests in OpenShift Virtualization. These users will often find themselves responsible for provisioning virtual guests, and day to day management of the guests, and the applications running within.

*Virtual Infrastructure Administrators* -- Those responsible for the physical infrastructure hosting the OpenShift Virtualization solution. These users will be responsible for physical hardware, storage, and networking changes to the environment, that will affect the day to day operations of the running virtual machines.


== What we have to do on original environment

1. Upgrade cluster to 4.19
2. Upgrade cluster to 4.20
3. Upgrade all operators
4. Define ocs-external-storagecluster-ceph-rbd-immediate StorageClass as default
5. Delete unnecessary namespace
6. Créer les namespace project-1 to 20 with associated role
7. Ajouter le role kubevirt.io:migrate aux utilisateurs

== Create new role

----
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'kubevirt.io:dm'
rules:
  - verbs:
      - get
      - delete
      - create
      - update
      - patch
      - list
      - watch
      - deletecollection
    apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachines/migrate
      - virtualmachines/pause
      - virtualmachines/unpause
      - virtualmachines/freeze
      - virtualmachines/unfreeze
      - virtualmachines/softreboot
      - virtualmachines/reset
  - verbs:
      - get
      - delete
      - create
      - update
      - patch
      - list
      - watch
      - deletecollection
    apiGroups:
      - kubevirt.io
    resources:
      - virtualmachineinstancemigrations
----


== Delete unnecessary namespace

----
for i in {1..20}
do 
oc delete namespace mtv-user$i
oc delete namespace oadp-user$i
oc delete namespace vmimported-user$i
oc delete namespace vmexamples-user$i-udn
done
----


== Create namespace

----
for i in {1..20}
do 
oc new-project project-$i
oc create ns udn-projet-$i --dry-run=client -o yaml | oc label -f - --local k8s.ovn.org/primary-user-defined-network="" -o yaml | oc apply -f -
oc adm policy add-role-to-user admin user$i -n project-$i
oc adm policy add-role-to-user admin user$i -n udn-projet-$i
oc adm policy add-role-to-user admin user$i -n openshift
oc adm policy add-role-to-user kubevirt.io:dm user$i -n project-$i
oc adm policy add-role-to-user edit user$i -n openshift-migration
done
----




== Version Information

This edition of the  OpenShift Virtualization Roadshow has been developed using the following software versions:

* Red Hat OpenShift 4.20
* Red Hat OpenShift Virtualization 4.20
* Red Hat OpenShift Data Foundation 4.20
* Red Hat Migration Toolkit for Virtual Machines 2.11

