Welcome to a custom OpenShift Virtualization Roadshow !

== Introduction
This repository hosts the lab guide for the OpenShift Virtualization Roadshow, which can be delivered by Red Hat Associates to customers and interested parties all over the world.

It is designed to work with the Showroom lab environment provided by the Red Hat Demo Platform (RHDP) team.

This roadshow event is organized to allow you to have a hands-on experience with Red Hat OpenShift Virtualization.

OpenShift Virtualization enables you to bring virtual machines onto a modern, Kubernetes-based infrastructure. It enables the development and delivery of new applications as well as the modernization of existing ones and can create applications that consist of virtual machines, containers, and serverless functions - all managed together using Kubernetes-native tools and paradigms.

In this event we will explore many common management activities that virtual administrators often encounter in their day to day workflows.

== Who Will Benefit Most from attending a Roadshow?

*Virtual Machine Administrators* -- Those responsible for day to day management of virtual guests in OpenShift Virtualization. These users will often find themselves responsible for provisioning virtual guests, and day to day management of the guests, and the applications running within.

*Virtual Infrastructure Administrators* -- Those responsible for the physical infrastructure hosting the OpenShift Virtualization solution. These users will be responsible for physical hardware, storage, and networking changes to the environment, that will affect the day to day operations of the running virtual machines.


== What we have to do on original environment

1. Upgrade cluster to 4.19
2. Upgrade cluster to 4.20
3. Upgrade all operators
4. Define ocs-external-storagecluster-ceph-rbd-immediate StorageClass as default
5. Delete unnecessary namespace
6. Créer les namespace project-1 to 20 with associated role
7. Ajouter le role kubevirt.io:migrate aux utilisateurs

== Create new role

----
oc apply -f - <<EOF
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'kubevirt.io:dm'
rules:
  - verbs:
      - get
      - delete
      - create
      - update
      - patch
      - list
      - watch
      - deletecollection
    apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachines/migrate
      - virtualmachines/pause
      - virtualmachines/unpause
      - virtualmachines/freeze
      - virtualmachines/unfreeze
      - virtualmachines/softreboot
      - virtualmachines/reset
  - verbs:
      - get
      - delete
      - create
      - update
      - patch
      - list
      - watch
      - deletecollection
    apiGroups:
      - kubevirt.io
    resources:
      - virtualmachineinstancemigrations
EOF
----


== Delete unnecessary namespace

----
for i in {1..20}
do 
oc delete namespace mtv-user$i
oc delete namespace oadp-user$i
oc delete namespace vmimported-user$i
oc delete namespace vmexamples-user$i-udn
done
----


== Create namespace

----
for i in {1..20}
do 
oc new-project project-$i
oc create ns udn-projet-$i --dry-run=client -o yaml | oc label -f - --local k8s.ovn.org/primary-user-defined-network="" -o yaml | oc apply -f -
oc adm policy add-role-to-user admin user$i -n project-$i
oc adm policy add-role-to-user admin user$i -n udn-projet-$i
oc adm policy add-role-to-user admin user$i -n openshift
oc adm policy add-role-to-user kubevirt.io:dm user$i -n project-$i
oc adm policy add-role-to-user edit user$i -n openshift-migration
done
----


== Delete old deployment and recreate the new one

----
for i in {1..20}
do
oc delete deployment showroom -n showroom-user$i
done
----


----
for i in {1..5}
do
oc apply -f - <<EOF
kind: Deployment
apiVersion: apps/v1
metadata:
  name: showroom
  namespace: showroom-user$i
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: showroom
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: showroom
    spec:
      restartPolicy: Always
      serviceAccountName: showroom
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: nginx
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: content
              mountPath: /data/www
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-pid
              mountPath: /var/run
          terminationMessagePolicy: File
          image: 'quay.io/rhpds/nginx:1.25'
        - resources: {}
          readinessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: content
          livenessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: GIT_REPO_URL
              value: 'https://github.com/davmartini/ocp-virt-lab-multi-users-custom'
            - name: GIT_REPO_REF
              value: main
            - name: ANTORA_PLAYBOOK
              value: default-site.yml
          ports:
            - containerPort: 8000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: user-data
              mountPath: /user_data/
            - name: showroom
              mountPath: /showroom/
          terminationMessagePolicy: File
          image: 'ghcr.io/rhpds/showroom-content:prod'
        - resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          name: terminal
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: GUID
              value: 26ljc
          ports:
            - containerPort: 7681
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: terminal-lab-user-home
              mountPath: /home/lab-user
          terminationMessagePolicy: File
          image: 'quay.io/rhpds/openshift-showroom-terminal-ocp:latest'
      serviceAccount: showroom
      volumes:
        - name: showroom
          emptyDir: {}
        - name: user-data
          configMap:
            name: showroom-userdata
            defaultMode: 420
        - name: content
          configMap:
            name: showroom-index
            defaultMode: 420
        - name: nginx-config
          configMap:
            name: showroom-proxy-config
            defaultMode: 420
        - name: nginx-pid
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: terminal-lab-user-home
          persistentVolumeClaim:
            claimName: showroom-terminal-lab-user-home
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
EOF
done
----




== Version Information

This edition of the  OpenShift Virtualization Roadshow has been developed using the following software versions:

* Red Hat OpenShift 4.20
* Red Hat OpenShift Virtualization 4.20
* Red Hat OpenShift Data Foundation 4.20
* Red Hat Migration Toolkit for Virtual Machines 2.11

